apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: presence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presence
  template:
    metadata:
      labels:
        app: presence
    spec:
      containers:
      - name: presence
        image: kruszczynski/presence-demo:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: presence-service
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: presence
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: presence-ingress
spec:
  rules:
  - host: presence.bartek.dev
    http:
      paths:
      - backend:
          serviceName: presence-service
          servicePort: 80
